### PR TITLE
Neon Lights

### PR DESCRIPTION
**Pull request by floatingbird-coder**
These are different colored lights for floating sandbox.

### CODE REVIEW

**Comment by GabrieleGiuseppini** [comment]
Hi, thanks for the PR! Have you checked whether it really works? The (yellow) color of the lights unfortunately does not come from the materials template, but in fact it comes from a shader.

**Comment by floatingbird-coder** [comment]
How do I test out the lights to see if they work or not?

**Comment by floatingbird-coder** [comment]
I tested it out, but it doesn't work. I don't know how to make it show. How do I?

**Comment by GabrieleGiuseppini** [comment]
Well, that's what I said above - unfortunately in this version the color for all lights is coded in the shader; you cannot change the color of individual lights. I have planned an optimization in the future that *might* also allow for different colors, at that moment I'll take your PR!

**Pull request closed without merging**
