### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sjohal21**
Added troubleshooting steps for Linux users using Wayland, as is the case with many newer distributions.

### CODE REVIEW

**Comment by sjohal21** [comment]
I would just like to add this is an upstream issue with wxWidgets, and not particular to Floating Sandbox, but it still affects this game.

**Comment by sjohal21** [comment]
A quick update - this issue is fixed in newer versions of wxWidgets!
I have compiled a version of the game, and although it was compiled with quite a few hacks to keep openSUSE happy (using the -lX11 flag in GCC and not using static libraries as using them would try to load from shared libraries), the game launches on GNOME using Wayland. However, there are some areas with white boxes around them (dials and the hook icon to the left) so this might possibly need a bit more work before a final build can use this.

**Comment by GabrieleGiuseppini** [comment]
That's fantastic news, thanks for the update!
The white areas might be due to transparency of the bitmaps not being supported? Can you attach a screenshot?

**Comment by sjohal21** [comment]
I was just about to provide a screenshot when I noticed that my automatic dark mode in GNOME has also been applied rather than white boxes, meaning this is likely a transparency issue.
Screenshot from 2021-11-14 21-03-04
.

**Comment by GabrieleGiuseppini** [comment]
Can you tell me what version of GTK this is?

**Comment by sjohal21** [comment]
It's GTK 4 running on Gnome 41. However, during the build, I did install GTK 3 libraries as per the Ubuntu instructions, so it may be running on 3.

**Pull request merged**
